In [ ]:
import numpy as np

In [ ]:
################################TASK 1
A = np.array([[1, 2, 1], [-2, 1, 1]])
B = np.array([[3, 1], [-1, 0], [2, 4]])
C = np.array([[-2, 2], [1, -1], [1, 2]])
R = A + 2*np.transpose(B)
print(R)
R = B+ 2*C
print(R)

[[7 0 5]
 [0 1 9]]
[[-1  5]
 [ 1 -2]
 [ 4  8]]


In [ ]:
##############################TASK2
A = np.zeros((8, 8), dtype=np.int32)
A[0:8:2, 1:8:2] = 1
A[1:8:2, 0:8:2] = 1
print(A)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
##########################TASK3
A = np.arange(0, 1.5, 0.1)
A = A.reshape(5, 3)
print(A)
B = np.arange(1, 7, 1)
B = B.reshape(3, 2)
print(B)
R = np.dot(A, B)
print(R)

[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]
 [0.9 1.  1.1]
 [1.2 1.3 1.4]]
[[1 2]
 [3 4]
 [5 6]]
[[ 1.3  1.6]
 [ 4.   5.2]
 [ 6.7  8.8]
 [ 9.4 12.4]
 [12.1 16. ]]


In [ ]:
##########################TASK4
A = np.arange(1, 72, 2, dtype = np.int32)
B = A[np.where(A % 3 == 0)]
print(A)
print(B)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71]
[ 3  9 15 21 27 33 39 45 51 57 63 69]
